aws_profile       = "default"
aws_account_no    = "471112672291"
aws_region        = "ap-southeast-2"
tag_type          = "devops"
vpc_name          = "abeginner"
sg_name           = "port-sydney-abeginner-443"
this_name         = "rhel86"
key_name          = "ed25519ansible"
aws_ami_prefix    = "RHEL-8.6.0_HVM"
ec2_instance_type = "t3a.medium"
volume_size       = 32
ticket            = "no"
created_by        = "abeginner"

iam_instance_profile_name = "whichRoleSSM"
