aws_profile     = "default"
aws_account_no  = "471112672291"
aws_region      = "ap-southeast-2"
this_name       = "eks-cluster-role"
created_by     = "adevopsbeginner"
link           = "https://www.youtube.com/@adevopsbeginner"
